version: '3'
services:
  freeradius:
    image: alpine-freeradius
    build: .
    restart: always
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - "./conf/clients.conf:/etc/raddb/clients.conf"
      - "./conf/users:/etc/raddb/users"
