[book]
authors = ["Masayoshi Kokuryo"]
multilingual = false
src = "book-src"
title = "dockers"

[build]
build-dir = "docs"
create-missing = false

[output.html]
additional-css = ["book-src/custom.css"]
