version: '3'
services:
  dhcpd:
    image: alpine-dhcpd
    build: .
    restart: always
    volumes:
      - ./conf/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./conf/dhcpd.leases:/var/lib/dhcp/dhcpd.leases
    ports:
      - "67:67"
    network_mode: host
